def fish_details(fish_class):
    fish_dict = {
        "Black Sea Sprat": "The Black Sea sprat, Clupeonella cultriventris, is a small fish of the herring family, Clupeidae. It is found in the Black Sea and Sea of Azov and rivers of its basins: Danube, Dnister, Dnipro (Ukraine), Southern Bug, Don, Kuban. It has white-grey flesh and silver-grey scales. A typical size is 10 cm (maximum 15 cm) The life span is of up to 5 years. The peak of its spawning is in April and it can be found in enormous shoals in sea-shores, filled all-round coastal shallows, moving quickly back in the sea at a depth of 6–30 metres. Used for food; it has around 12% fat in flesh.",
        "Gilt-Head Bream": "The gilt-head bream, known as Orata in antiquity and still today in Italy, is a fish of the bream family Sparidae found in the Mediterranean Sea and the eastern coastal regions of the North Atlantic Ocean. It commonly reaches about 35 centimetres in length, but may reach 70 cm and weigh up to about 7.36 kilograms.",
        "Horse Mackerel": "The Atlantic horse mackerel, also known as the European horse mackerel or common scad, is a species of jack mackerel in the family Carangidae, the jacks, pompanos and trevallies. It is found in the eastern Atlantic Ocean off Europe and Africa and into the south-eastern Indian Ocean.",
        "Red Mullet": 'The red mullets or surmullets are two species of goatfish, Mullus barbatus and Mullus surmuletus, found in the Mediterranean Sea, east North Atlantic Ocean, and the Black Sea. Both "red mullet" and "surmullet" can also refer to the Mullidae in general.',
        "Red Sea Bream": "Pagrus major or red seabream is a fish species in the family Sparidae. It is also known by its Japanese name, madai. The fish has high culinary and cultural importance in Japan, and is also frequently eaten in Korea and Taiwan.",
        "Sea Bass": "Sea bass is a common name for a variety of different species of marine fish. Many fish species of various families have been called sea bass.",
        "Shrimp": "Shrimp are decapod crustaceans with elongated bodies and a primarily swimming mode of locomotion – most commonly Caridea and Dendrobranchiata. More narrow definitions may be restricted to Caridea, to smaller species of either group or to only the marine species.",
        "Striped Red Mullet": "The striped red mullet or surmullet is a species of goatfish found in the Mediterranean Sea, eastern North Atlantic Ocean, and the Black Sea. They can be found in water as shallow as 5 metres or as deep as 409 metres depending upon the portion of their range that they are in.",
        "Trout": "Trout are species of freshwater fish belonging to the genera Oncorhynchus, Salmo and Salvelinus, all of the subfamily Salmoninae of the family Salmonidae. The word trout is also used as part of the name of some non-salmonid fish such as Cynoscion nebulosus, the spotted seatrout or speckled trout."
    }

    return fish_dict[fish_class]
